[tool.black]
line-length = 127
target-version = ['py310']
include = '\.pyi?$'
extend-exclude = '''
/(
    \.venv
  | venv
  | __pycache__
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 127
known_first_party = ["app", "core", "handlers"]


[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poe.tasks]
# Основные команды
run = "python app/main.py"
install = "pip install -r requirements.txt"
dev-install = "pip install -r requirements-dev.txt"
update = "pip install --upgrade -r requirements.txt"

# Создание виртуального окружения
venv = "python -m venv venv && echo '✅ Виртуальное окружение создано' && echo 'Активируй: source venv/bin/activate (Linux/Mac) или .\\venv\\Scripts\\activate (Windows)'"

# Команды для кодстайла
format = "python -m black . && python -m isort ."
lint = "python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics && python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics"
check = "python -m black --check . && python -m isort --check-only . && python -m flake8 ."
quick-lint = "python -m flake8 . --select=E9,F63,F7,F82 --exit-zero"

# Очистка
clean = "find . -name '*.pyc' -delete && find . -name '__pycache__' -exec rm -rf {} + && echo '🧹 Кэш очищен!'"

# Составные задачи
setup = ["install", "run"]
dev-setup = ["dev-install", "run"]
full-check = ["format", "lint"]
restart = ["clean", "run"]